sudo: false
language: ruby
cache: bundler
rvm:
  - 2.3
  - 2.4
  - ruby-head
before_script:
  - bin/rails db:migrate RAILS_ENV=test
  - bin/rails system_tester:migrate
script: bin/rails test
matrix:
 allow_failures:
   - rvm: ruby-head
